// Code generated by "stringer -type=Deploy -linecomment"; DO NOT EDIT.

package env

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DeployUnknown-0]
	_ = x[DeployLocal-1]
	_ = x[DeployDev-2]
	_ = x[DeployTest-3]
	_ = x[DeployUat-4]
	_ = x[DeployProd-5]
}

const _Deploy_name = "unknownlocaldevtestuatprod"

var _Deploy_index = [...]uint8{0, 7, 12, 15, 19, 22, 26}

func (i Deploy) String() string {
	if i < 0 || i >= Deploy(len(_Deploy_index)-1) {
		return "Deploy(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Deploy_name[_Deploy_index[i]:_Deploy_index[i+1]]
}
